# Generated by Django 5.2.6 on 2025-09-07 06:08

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='カテゴリ名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inquiry.category')),
            ],
            options={
                'verbose_name': 'カテゴリ',
                'verbose_name_plural': 'カテゴリ',
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='件名')),
                ('content', models.TextField(verbose_name='内容')),
                ('customer_name', models.CharField(max_length=100, verbose_name='顧客名')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='顧客メールアドレス')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='顧客電話番号')),
                ('status', models.CharField(choices=[('new', '新規'), ('in_progress', '対応中'), ('waiting', '保留'), ('resolved', '解決済み'), ('closed', '完了')], default='new', max_length=20, verbose_name='ステータス')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('urgent', '緊急')], default='medium', max_length=20, verbose_name='優先度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解決日時')),
                ('tags', models.CharField(blank=True, help_text='カンマ区切りで入力', max_length=500, verbose_name='タグ')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='担当者')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inquiry.category', verbose_name='カテゴリ')),
            ],
            options={
                'verbose_name': '問い合わせ',
                'verbose_name_plural': '問い合わせ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='inquiry_attachments/', verbose_name='ファイル')),
                ('filename', models.CharField(max_length=255, verbose_name='ファイル名')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='inquiry.inquiry', verbose_name='問い合わせ')),
            ],
            options={
                'verbose_name': '添付ファイル',
                'verbose_name_plural': '添付ファイル',
            },
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_public', models.BooleanField(default=True, verbose_name='公開')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='閲覧回数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('tags', models.CharField(blank=True, help_text='カンマ区切りで入力', max_length=500, verbose_name='タグ')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inquiry.category', verbose_name='カテゴリ')),
                ('related_inquiries', models.ManyToManyField(blank=True, to='inquiry.inquiry', verbose_name='関連問い合わせ')),
            ],
            options={
                'verbose_name': 'ナレッジ',
                'verbose_name_plural': 'ナレッジ',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='対応内容')),
                ('is_internal', models.BooleanField(default=False, help_text='顧客には表示されない内部メモ', verbose_name='内部メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='inquiry.inquiry', verbose_name='問い合わせ')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='対応者')),
            ],
            options={
                'verbose_name': '対応履歴',
                'verbose_name_plural': '対応履歴',
                'ordering': ['-created_at'],
            },
        ),
    ]
