# Generated by Django 5.2.6 on 2025-09-08 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('inquiry', '0002_tag_remove_inquiry_tags_inquiry_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.category', verbose_name='カテゴリ'),
        ),
        migrations.RemoveField(
            model_name='knowledge',
            name='category',
        ),
        migrations.RemoveField(
            model_name='knowledge',
            name='author',
        ),
        migrations.RemoveField(
            model_name='knowledge',
            name='related_inquiries',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='tags',
            field=models.ManyToManyField(blank=True, to='common.tag', verbose_name='タグ'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Knowledge',
        ),
    ]
