# Generated by Django 5.2.6 on 2025-09-08 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('inquiry', '0003_remove_category_parent_alter_inquiry_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_public', models.BooleanField(default=True, verbose_name='公開')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='閲覧回数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('tags', models.CharField(blank=True, help_text='カンマ区切りで入力', max_length=500, verbose_name='タグ')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.category', verbose_name='カテゴリ')),
                ('related_inquiries', models.ManyToManyField(blank=True, to='inquiry.inquiry', verbose_name='関連問い合わせ')),
            ],
            options={
                'verbose_name': 'ナレッジ',
                'verbose_name_plural': 'ナレッジ',
                'ordering': ['-updated_at'],
            },
        ),
    ]
