services:
  web:
    build:
      context: .
      target: web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./media:/var/media
      - ./staticfiles:/var/staticfiles
      - ./media/temp:/var/temp
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - DJANGO_SECRET_KEY=${SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - USE_TAILWIND_CDN=${USE_TAILWIND_CDN}
